.github/workflows/release.yml
go.mod

- Adds `go.mod` reference to retract prematurely released versions.
- Adds GitHub action to implement go.pkg.dev update with mandatory version increase to v1.7.10

fix(Issue): #39 - Correct broken pkg.go.dev versioning

---

docs/arguments.md
internal/flags/flags.go
internal/flags/flags_test.go

Updates minimum supported Docker API version.

Fix: Issue #64 - Watchtower Container Update Failure

---

.github/workflows/release-dev.yaml

This commit updates the `release-dev.yaml` workflow to replace the outdated `jerray/publish-docker-action` with Docker's official actions (`docker/setup-buildx-action`, `docker/login-action`, and `docker/build-push-action`). It also pins action versions using commit digests for reproducibility and security. The workflow now explicitly targets `linux/amd64` for dev builds and includes improved configuration for building and pushing images to Docker Hub and GHCR.
Key changes:
- Replaced `jerray/publish-docker-action` with Docker's official actions.
- Pinned action versions using commit digests instead of tags.
- Added explicit `linux/amd64` platform specification for builds.
- Improved reliability, security, and maintainability of the workflow.
These changes ensure better integration with …

Update workflow to use Docker's official actions and digests

---

pkg/container/client.go
pkg/container/client_test.go

Ensure that static MAC addresses defined in Docker Compose files are preserved during container updates by explicitly copying the MacAddress field in GetNetworkConfig. 
Added comprehensive test coverage in client_test.go, including:
- Unit tests for GetNetworkConfig with single and multiple networks
- Integration test for StartContainer to validate MAC address application
This resolves the issue where Watchtower updates assigned random MAC addresses, disrupting DHCP-based IP assignments.
Fixes: containrrr/watchtower #1941

fix(container): preserve static MAC address in StartContainer with additional test coverage

---

pkg/api/api.go

Previously, RunHTTPServer returned a wrapped "server shutdown failed: context canceled" error when the context was canceled before shutdown completed, causing test failures in the Docker build environment (golang:alpine). This was inconsistent with the intended behavior where cancellation should gracefully stop the server without error.
This commit:
- Adds a serverShutdownTimeout constant (5 seconds) to replace the magic number for shutdown timeout.
- Creates a new shutdown context with this timeout in RunHTTPServer, ensuring shutdown has time to complete.
- Treats context.Canceled as a non-error case, returning nil instead of a wrapped error.
This resolves the failing "should register and serve requests via RegisterHandler" test in api_test.go during Docker builds while maintaining …

fix(api): Handle context cancellation gracefully in RunHTTPServer

---

docs/arguments.md
docs/usage-overview.md

Adds both a note in the usage and environment variable sections to help bring awareness regarding a known issue with Watchtower and Docker API versioning.
This issue is noted in https://github.com/nicholas-fedor/watchtower/issues/87
API Version-related issues have also been noted in Beatkind's fork of Watchtower after updating from the original repo:
https://github.com/beatkind/watchtower/issues/88
https://github.com/beatkind/watchtower/issues/114
https://github.com/beatkind/watchtower/issues/123

Improve documentation regarding Docker API version

---

go.mod
go.sum
pkg/container/container_source.go

This PR fixes an issue where Watchtower failed to recreate containers on the default `bridge` network due to invalid network settings. The error "invalid config for network bridge: invalid endpoint settings" occurred because `getNetworkConfig` set `Aliases` and `DNSNames`, which are unsupported on the default bridge network. 
Changes:
- Updated `getNetworkConfig` to exclude `Aliases` and `DNSNames` for the "bridge" network, preserving other settings like IP and MAC addresses.
- Tested with `redis:7-alpine` after pruning, verifying successful updates without errors.
- Updated to Go 1.24.2 and onsi/gomega v1.37.0

fix(network): exclude Aliases and DNSNames on default bridge network

---

.github/workflows/build.yaml
.github/workflows/release-dev.yaml
goreleaser.yml

Incorrectly attempted to use Goreleaser's snapshot functionality. 
As not using Pro version, nightlies are not available. 
Migrating to different workflow that builds and publishes the Docker/GHCR images.

fix(release-dev): correct misconfigured dev build workflow

---

cmd/root.go
docs/notifications.md
internal/actions/update.go
pkg/container/container_source.go
pkg/container/container_target.go
pkg/container/image.go
pkg/notifications/common_templates.go
pkg/notifications/shoutrrr.go
pkg/notifications/shoutrrr_test.go

- Fixed missing container/image info in notifications by updating default-legacy template to use logrus fields
- Revised template to past tense ("Stopped", "Removed") and removed signal for consistency and brevity
- Added debug logging in shoutrrr.go for message generation and sending
- Updated Notifications.md to document new template and behavior
- Adjusted test to remove trailing newline expectation

feat(notifications): enhance default-legacy template with fields and debug logging

---

README.md
docs/arguments.md
docs/http-api-mode.md
pkg/filters/filters.go
pkg/filters/filters_test.go
pkg/notifications/notifier_test.go

Adapted work from https://github.com/containrrr/watchtower/pull/2054.
> To be able to do finegrained updates to container running a specific tag of an image i added this.
If an API update includes a tag in its image filter, it will not be ignored, but it's still possible to provide a tagless image name.

Optional tag filter

---

cmd/root.go
docs/arguments.md
internal/flags/flags.go
internal/flags/flags_test.go
pkg/container/client.go
pkg/container/container_target.go
pkg/container/container_test.go

Add `--disable-memory-swappiness` flag to set container MemorySwappiness to nil, addressing Podman compatibility with crun and cgroupv2, as proposed by https://github.com/containrrr/watchtower/pull/2072.
Changes include:
- Implemented flag logic to set MemorySwappiness to nil
- Added flag parsing and validation
- Updated CLI command configuration
- Added unit tests for flag functionality
- Documented flag in arguments

feat: add DisableMemorySwappiness flag for Podman compatibility

---

pkg/container/container_mock_test.go
pkg/container/container_test.go

- Add a unit test to verify that `GetCreateHostConfig` preserves volume subpath in `HostConfig.Mounts`, addressing potential issues with subpath handling during container recreation.
- Add a `WithMounts` helper in `container_mock_test.go` to support mount configuration in tests.
Successful testing confirms that this fork of Watchtower honors Docker volume subpaths, including avoiding the issue described in https://github.com/containrrr/watchtower/issues/2017

test(container): add unit test for volume subpath preservation

---

cmd/root.go

Migrate logging level from info to debug.
This is more appropriate for this level of operation.
Should resolve issue https://github.com/nicholas-fedor/watchtower/issues/281

fix: correct logging level of watchtower handling for shutdown signals and context cancellation

---

pkg/container/container_source.go

- Demote the logging messages in `debugLogMacAddress` function to debug.
Closes #313

fix(container): demote log messages to debug

---

docs/arguments.md
internal/flags/flags.go
pkg/container/client_test.go
pkg/container/container_source.go

This PR enhances the container stop functionality in Watchtower by increasing the default timeout and reducing log verbosity:
- **Increased default timeout**: Changed the default container stop timeout from 10 seconds to 30 seconds in `flags.go` (`defaultStopTimeoutSeconds`) to allow more time for containers to stop gracefully, improving reliability for slower workloads.
- **Demoted log level**: Modified the "Container did not stop within timeout" log message in `container_source.go` (`stopAndRemoveContainer`) from warning to debug to reduce user-facing log noise while preserving diagnostic details.
- **Updated test**: Fixed the failing `TestContainer` test in `client_test.go` by capturing debug-level logs, using a 100ms timeout, and adding a 200ms mock server delay to simulate timeout …

Increase Default Container Stop Timeout to 30s and Demote Timeout Log to Debug

---

.gitattributes

- Enforce LF line endings for text files.
- Mark common binary files to prevent line-ending normalization.

chore(git): add .gitattributes file

---

internal/util/util.go

- Update `SliceSubtract` to use the standard library's recently implemented `slices.Contains` functionality.
- Correct and update `SliceSubtract` function comments.

chore(util): refactor `SliceSubtract` and update comment

---

internal/actions/actions_suite_test.go
internal/actions/mocks/client.go
internal/actions/update.go
internal/actions/update_test.go

This change addresses the issue where Watchtower incorrectly updated containers with pinned images by enhancing the `isPinned` function to properly detect digest-based references. It partially resolves #345 by improving image reference handling, though further work is needed for HEAD request failures.
- Added `isPinned` function in `update.go` to detect digest-based image references (`reference.Digested` and `reference.NamedTaggedDigested`), skipping staleness checks for pinned images.
- Updated `internal/actions/mocks/client.go` to include `IsContainerStaleCount` in `TestData`, enabling test verification of skipped staleness checks.
- Added test cases in `update_test.go` to cover tagged, untagged, pinned, and invalid image references.
Closes: #345 (partial fix)

fix(update): ensure pinned container images are skipped during updates

---

go.mod
pkg/container/client.go
pkg/container/container.go
pkg/container/container_mock_test.go
pkg/container/container_target.go
pkg/container/container_test.go

Fixes a bug where container updates failed when connected to multiple networks in Docker API versions < 1.44 (e.g., `grafana/grafana`, `ghcr.io/linuxserver/changedetection.io`). The issue occurred because `ContainerCreate` does not support multiple network endpoints in legacy APIs. The solution modifies `StartTargetContainer` to create containers with a single network and attach additional networks sequentially, with comprehensive test coverage.
Fixes #346.
- Modified `StartTargetContainer` to handle multiple networks for API < 1.44 by using the first network for creation and attaching others via `attachNetworks`.
- Added `attachNetworks` function to connect additional networks sequentially for legacy API compatibility.
- Updated `container_test.go` with tests for `getNetworkConfig` in …

Resolve container update failure with multiple networks (#346)

---

.golangci.yaml
internal/flags/flags_test.go
pkg/api/update/update.go
pkg/container/cgroup_id_test.go
pkg/container/container_source.go
pkg/filters/filters_test.go
pkg/metrics/metrics_test.go
pkg/notifications/shoutrrr.go
pkg/notifications/shoutrrr_test.go
pkg/registry/digest/digest.go
pkg/registry/digest/digest_test.go
pkg/session/progress_test.go
pkg/session/report_test.go

This pull request addresses [Issue #366](https://github.com/nicholas-fedor/watchtower/issues/366) by fixing HEAD request failures for unauthenticated registries, ensuring `fetchDigest` proceeds correctly when no authentication is required. It also includes linting updates to modernize the linter configuration and resolve warnings, maintaining code quality.
- **chore(lint): deprecate wsl linter and update to wsl_v5**
- Updated linter configuration to use `wsl_v5`, replacing the deprecated `wsl` linter.
- **fix(lint): suppress revive var-naming for util and types packages**
- Added exclusion rules in `.golangci.yaml` to ignore 'avoid meaningless package names' for `internal/util` and `pkg/types`.
- Resolved golangci-lint warnings in `doc.go` and `report.go`.
- **chore(lint): add newlines to …

fix(registry): handle unauthenticated registries and update linting (#366)

---

docs/arguments.md

This pull request updates the `arguments.md` documentation to include missing environment variables for registry authentication: `REPO_USER`, `REPO_PASS`, and `DOCKER_CONFIG`. These additions address user confusion noted in GitHub discussion #389 regarding Docker Hub authentication via environment variables. The `REPO_PASS` note has been updated to include concise guidance on using Docker secrets for secure configuration, aligning with Watchtower's support for file-based secrets.

Add Missing Environment Variables to `arguments.md`

---

.github/workflows/security.yaml

This pull request resolves gosec flagging issues in test files by removing the `-tests` flag from the gosec action in `security.yaml`. This reverts to gosec's default behavior of skipping test files, focusing scans on production code only.
- Updated `gosec` step args to: `-no-fail -fmt sarif -out results.sarif ./...`
No breaking changes; security scans remain effective for main code paths.

Fix Gosec Flagging Issues in Test Files

---

.circleci/config.yml
.circleci/continue-config.yml

This pull request optimizes CircleCI workflows to run tests conditionally only when Go-related files (e.g., cmd/, internal/, pkg/, main.go, go.mod, go.sum) are changed, using dynamic configuration with the path-filtering orb. This reduces inefficiency by skipping unnecessary test runs on non-production code changes like workflows or docs.
- Split CircleCI config into `config.yml` (setup with path filtering) and `continue-config.yml` (conditional build job).

Optimize CI Workflows for Non-Go Changes

---

build/goreleaser/dev.yml
build/goreleaser/prod.yml

This PR addresses an issue in the GoReleaser configuration where multiple build sections shared the same implicit ID, leading to the error: "found 2 builds with the ID 'watchtower', please fix your config".
By assigning unique IDs (`watchtower-multiarch` and `watchtower-armv6`) to the build configurations in `dev.yml` and `prod.yml`, the build process can now distinguish between the multi-architecture and ARMv6-specific builds.
- Updated `build/goreleaser/dev.yml` with unique build IDs.
- Updated `build/goreleaser/prod.yml` with unique build IDs for consistency.

fix(ci): add unique IDs to GoReleaser build configs

---

.github/workflows/release-dev.yaml

This PR fixes issues in the development release workflow where Docker image builds failed due to missing binary paths during cache key computation. The errors stemmed from nested artifact directories and mismatched architecture naming for ARMv6.
By adjusting the artifact download path to the current directory and correcting the `norm_arch` for ARMv6, the workflow now correctly locates the binaries built by GoReleaser.
- Updated `.github/workflows/release-dev.yaml`:
- Set artifact download `path` to `.`.
- Changed `norm_arch` for `arm/v6` to `arm_v6`.

fix(ci): correct artifact download path and ARMv6 arch in dev workflow

---

build/docker/Dockerfile.dev

This PR addresses ongoing failures in the dev image build process where binaries were not found due to an incorrect path in the Dockerfile. The artifacts from GoReleaser are downloaded to the root directory, but the COPY instruction referenced a nested `/dist` path.
By removing `/dist` from the COPY line, the build can now locate the binaries properly.
- Updated `build/docker/Dockerfile.dev`:
- Changed COPY to `${PREFIX}_${TARGETOS}_${TARGETARCH}/watchtower /watchtower`.

fix(ci): remove dist/ from binary COPY in dev Dockerfile

---

.github/workflows/release-dev.yaml

This PR fixes the remaining build failure in the dev workflow for the ARMv6 architecture, where the binary path did not match GoReleaser's output directory naming.
By adjusting `norm_arch` to `arm_6`, the path now aligns with the generated directory (e.g., `watchtower-armv6_linux_arm_6/watchtower`).
- Updated `.github/workflows/release-dev.yaml`:
- Set `norm_arch` for `arm/v6` to `arm_6`.

fix(ci): correct norm_arch for ARMv6 in dev workflow

---

.github/workflows/release-prod.yaml

This PR ensures the production release workflow behaves appropriately during dry runs by skipping unnecessary steps, aligning with the intent of a test run. Previously, the workflow updated Go documentation and uploaded binary SBOMs even in dry runs, which could lead to unintended changes or artifacts.
- Updated `release-prod.yaml`:
- Added `if: inputs.dry_run != true` to the `Update-Go-docs` job.
- Added `if: inputs.dry_run != true` to the `Upload binary SBOMs` step in the `Build` job.

fix(ci): skip docs update and artifact uploads in prod dry run

---

.github/workflows/release-prod.yaml

This PR fixes a flag compatibility issue in the production release workflow's dry run mode. GoReleaser v2 changed the skipping flag from --skip-publish to --skip=publish, causing errors in dry runs.
- Updated `release-prod.yaml`:
- Changed dry run args to '--snapshot --clean --skip=publish'.

fix(ci): update GoReleaser dry run flags in prod workflow

---

.github/workflows/release-prod.yaml

This PR fixes an error in the production workflow where GoReleaser fails to generate SBOMs due to missing Syft executable. Syft is a dependency for the SBOM artifacts configured in prod.yml.
- Updated `release-prod.yaml`:
- Added "Install Syft" step before running GoReleaser using the official install script.

fix(ci): install Syft for SBOM generation in prod workflow

---

.github/workflows/release-dev.yaml

This PR fixes SBOM generation failures for non-amd64 images in the dev workflow by pulling images locally with --platform and using docker:// source for Syft. This avoids platform mismatch errors (e.g., armhf on amd64 runners) by ensuring images are available in the Docker daemon. Error handling and cleanup steps improve reliability.
- Updated `release-dev.yaml`:
- Added "Pull per-arch image for SBOM" step with error handling.
- Added "Pull manifest images for SBOM" step in Create-Manifest-and-Attest.
- Used docker:// prefix in SBOM steps for explicit local scanning.
- Added cleanup step to remove pulled images.

fix(ci): pull images locally for SBOM scan in dev workflow

---

.github/workflows/release-dev.yaml

This PR fixes SBOM generation failures due to invalid image reference formats (e.g., `//nickfedor/watchtower:armhf-dev`) caused by the docker:// prefix in anchore/sbom-action. Removing the prefix allows Syft to use the local Docker daemon, leveraging images pulled with --platform.
- Updated `release-dev.yaml`:
- Removed docker:// from image inputs in per-arch and manifest SBOM steps.
- Kept the "Pull manifest images for SBOM" step to avoid potential platform issues.

fix(ci): remove docker:// prefix from SBOM image references in dev workflow

---

.github/workflows/release-dev.yaml

This PR fixes 401 Unauthorized errors during Docker Hub attestation uploads in the dev workflow. The actions/attest-build-provenance action requires explicit registry authentication for Docker Hub, which wasn’t being applied correctly despite successful image pushes.
- Updated `release-dev.yaml`:
- Added `github-token: ${{ secrets.DOCKERHUB_TOKEN }}` to `Attest per-arch Docker Hub image` and `Attest Docker Hub manifest` steps.
- Added `Verify Docker Hub auth` steps before attestations to debug authentication issues.

fix(ci): add Docker Hub token to attestation steps in dev workflow

---

.github/workflows/release-dev.yaml
.github/workflows/release-prod.yaml

Enable Docker Buildx in `release-dev.yaml` and `release-prod.yaml` to support SBOM and provenance attestations:
- Add `setup-qemu-action@v3` for multi-platform emulation.
- Add `setup-buildx-action@v3` to create Buildx builder with containerd store.
- Place before "Run GoReleaser" to resolve "Attestation not supported for docker driver" error.

ci: enable Buildx for attestations in dev and prod workflows

---

build/goreleaser/dev.yml
build/goreleaser/prod.yml

- Add --output=type=docker to dev.yml build_flag_templates for local image loading with --skip=publish.
- Add --output=type=registry to prod.yml for direct registry pushes.

ci: use explicit Buildx outputs for dev and prod builds

---

.github/workflows/build.yaml
.github/workflows/release-dev.yaml
.github/workflows/release-prod.yaml
build/goreleaser/dev.yml
build/goreleaser/prod.yml

- Refactor `release-prod.yaml` and `release-dev.yaml` to call consolidated `build.yaml` workflow for production and development builds, improving maintainability and reducing duplication
- Rename jobs to `build` in `release-prod.yaml` and `release-dev.yaml` for consistency
- Correct `build_flag_templates` in `prod.yml` from `--output=type=registry` to `--output=type=image` to ensure proper Docker image creation
- Correct `build_flag_templates` in `dev.yml` from `--output=type=docker` to `--output=type=image` to fix invalid output type
- Remove redundant comment in `release-dev.yaml` permissions for clarity
- Rename `release-prod.yaml` to `Release Production` and `release-dev.yaml` to `Release Development` for consistent naming

fix(workflows): refactor build workflows and correct output types

---

.github/workflows/release-dev.yaml

- Add `attestations: write` and `id-token: write` to `release-dev.yaml` permissions to resolve validation error when calling `build.yaml`, ensuring Docker image attestations can be generated

fix(workflows): add attestations and id-token permissions to release-dev

---

.github/workflows/build.yaml

- Update GoReleaser version in `build.yaml` from v2.3.2 to ~> v2 to resolve YAML unmarshal error by supporting `goriscv64` field in `prod.yml` and `dev.yml`

fix(goreleaser): update GoReleaser version to ~> v2 to support goriscv64

---

build/goreleaser/dev.yml
build/goreleaser/prod.yml

- Update `build_flag_templates` in `dev.yml` and `prod.yml` to conditionally use --load for dry-run builds (local loading) and --push for actual releases (registry push), resolving syntax and manifest list export errors in dry-run mode
- Maintain conditional skipping of attestations in dry-run to ensure compatibility with local Docker exporter, while preserving full functionality for non-dry-run releases

fix(goreleaser): use --load for dry-run and --push for releases

---

build/docker/Dockerfile
build/goreleaser/dev.yml
build/goreleaser/prod.yml

- Add goos: linux, goarch, and goamd64: "v1" (for amd64) to dockers entries in dev.yml and prod.yml to align with the builds section and ensure correct binary matching
- Add goarm: "6" to arm dockers to match the linux_arm_6 binary path
- Add --build-arg flags to build_flag_templates to pass GOOS, GOARCH, GOAMD64, GOARM, and GORISCV64 to the Dockerfile, enabling dynamic binary path resolution
- Update Dockerfile to copy the binary from the variant-specific path (e.g., dist/watchtower_linux_arm64/watchtower) using build arguments, fixing the "docker buildx build requires 1 argument" error

fix(goreleaser): align dockers with builds and update Dockerfile for binary paths

---

.github/workflows/build.yaml
.github/workflows/release-dev.yaml
.github/workflows/release-prod.yaml
build/docker/Dockerfile
build/goreleaser/dev.yml
build/goreleaser/prod.yml

This PR fixes a GHCR push permission error in the development and production release workflows and resolves a Dockerfile warning for an undefined `BASE_IMAGE` variable. It also removes redundant filename comments from workflow and configuration files.
- **build.yaml**: Added `packages: write` permission to ensure GHCR push access.
- **release-dev.yaml/release-prod.yaml**: Added `packages: write` to `manifest` job for consistent GHCR permissions.
- **Dockerfile**: Updated `org.opencontainers.image.base.name` label to use `${BASE_IMAGE:-alpine:3.22.1}` to fix undefined variable warning.
- **dev.yml/prod.yml**: Removed redundant filename comments.

fix(workflow): add package write permissions and fix Dockerfile base image label

---

.github/workflows/build.yaml

This PR resolves an error in the production release workflow where SBOM generation failed due to the `syft` executable not being found. The fix adds a step to install Syft in the `build.yaml` workflow for production builds, ensuring compatibility with the `sboms` configuration in `prod.yml`.
- **build.yaml**: Added a step to install Syft using the official installation script (`curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh`) before running GoReleaser, conditional on `build-type: prod`.

fix(build): add Syft installation step for prod builds

---

build/docker/Dockerfile

This PR fixes an issue in the Dockerfile where the binary copy destination led to it not being found on container launch. The change reverts the destination to the root path (/) as previously configured.

fix(dockerfile): correct binary copy path in Dockerfile

---

build/goreleaser/dev.yml
build/goreleaser/prod.yml

Disable CGO in GoReleaser configs to produce static binaries compatible with scratch image.
- Add env: - CGO_ENABLED=0 to builds in prod.yml
- Add env: - CGO_ENABLED=0 to builds in dev.yml

fix(goreleaser): disable CGO for static binaries

---

build/goreleaser/dev.yml

Remove "SNAPSHOT" from development build version strings by configuring GoReleaser's snapshot.name_template to use the latest tag and short commit hash.
- Added snapshot.name_template in dev.yml to set version as {{ .Tag }}-{{ .ShortCommit }}

chore(goreleaser): add snapshot name template to dev configuration

---

build/goreleaser/dev.yml
build/goreleaser/prod.yml

Remove build id from GoReleaser binary build configurations. This avoids issue of binaries with undesirable naming convention.

chore(goreleaser): remove goreleaser binary build id

---

build/goreleaser/prod.yml

- Use tag instead of version for image templates
- Allow SBOM generation for any artifacts (binaries and archives)

chore(goreleaser): minor prod.yaml corrections

---

build/docker/Dockerfile

Passes the BASE_IMAGE in the `build/docker/Dockerfile` to ensure successful builds and resolve linter warnings.
**Changes**:
- Added `ARG BASE_IMAGE` in the `scratch` stage to make `$BASE_IMAGE` available for the `org.opencontainers.image.base.name` label, resolving Buildkit's `UndefinedVar` warning.
- Simplified the `org.opencontainers.image.base.name` label by removing the redundant default value (`${BASE_IMAGE:-alpine:3.22.1}`).

chore(dockerfile): add ARG BASE_IMAGE in scratch stage

---

.github/workflows/create-manifests.yaml
build/goreleaser/prod.yml

This includes changes to both the GoReleaser configuration and the multi-platform image manifest generation workflow that removes the "v" prefix from image tags.
This reverts a previous change that inadvertently introduced them and should ensure the next release maintains the unprefixed tagging standard.
I anticipate that this should also resolve the issue noted in bug report #543 where inconsistent tagging resulted in the parsing failure.
Fixes #543

build: remove prefix from image tags

---

.github/workflows/publish-docs.yaml

Change working directory before building and deploying mkdocs site

ci(docs): correct build directory

---

.github/workflows/publish-docs.yaml
build/mkdocs/mkdocs.yaml

This implements the Mike plugin and uses "dev" tag for bleeding-edge and "latest" for releases. 
Default view is "latest".
- Enable versioning via the Mike plugin
- Add dynamic tagging to ensure correct versioning

docs: implement mkdocs-mike versioning

---

docs/assets/styles/extra.css
docs/assets/styles/theme.css
docs/overrides/main.html

Improve the documentation site by widening the content area and ensuring consistent background rendering.
- Increase `.md-grid` `max-width` to `80rem` with responsive breakpoints in `extra.css`
- Inline CSS in `main.html` to set background colors for light and dark modes
- Add link to latest version in `outdated` block using `config.site_url`

docs: improve content width and background consistency

---

.github/workflows/build.yaml

Remove the `Upload binary SBOMs` step from `build.yaml` as it is not needed. SBOMs are published by GoReleaser.
- Remove the `Upload binary SBOMs` step from `build.yaml`.

ci(build): remove unnecessary SBOM upload step

---

.github/workflows/create-manifests.yaml
.github/workflows/publish-docs.yaml

This PR addresses ShellCheck SC2086 warnings in the `create-manifests.yaml` and `publish-docs.yaml` GitHub Actions workflows. The warnings were caused by unquoted variables, which could lead to globbing or word splitting issues.
- `create-manifests.yaml`: Quoted `${VERSION}` in `docker buildx imagetools create` commands for production builds.
- `publish-docs.yaml`: Quoted `${{ steps.mike.outputs.version }}` and `${{ steps.mike.outputs.aliases }}` in the `mike deploy` command.

Fix ShellCheck SC2086 Warnings in CI Workflows

---

.github/workflows/publish-docs.yaml

This PR resolves ShellCheck SC2086 warnings in `publish-docs.yaml` by addressing unquoted variables that could lead to globbing or word splitting.
- Quoted `$GITHUB_OUTPUT` in `echo` commands in the `Determine Mike Version and Aliases` step.
- Reformatted `mike deploy` command to use multi-line syntax with backslash continuation, retaining quotes around `${{ steps.mike.outputs.version }}` and `${{ steps.mike.outputs.aliases }}`.

Fix ShellCheck SC2086 Warnings in Publish Docs Workflow

---

.github/workflows/publish-docs.yaml
build/mkdocs/mkdocs.yaml

Configures the documentation site to default to the latest release version instead of `dev`, addressing the "You're not viewing the latest version" message.
- Modified `publish-docs.yaml` to assign `latest` alias only during releases, deploying non-release pushes to `dev` without aliases.
- Added `alias_type: redirect` to `mkdocs.yaml` to ensure aliases use HTML redirects compatible with GitHub Pages.

docs: set latest release as default version

---

docs/overrides/main.html

- Update docs/overrides/main.html to use config.extra.version for suppressing outdated warning on dev pages.

docs: refine outdated warning condition for dev version

---

docs/overrides/main.html

- Update docs/overrides/main.html to use config.plugins['mike'].version for dev warning suppression.

docs: Update outdated warning condition to use mike version

---

docs/overrides/main.html

- Update docs/overrides/main.html to check config.site_url.endswith('/dev/') for suppressing outdated warning on dev pages.

docs: Update outdated warning condition to use site_url for dev

---

cmd/root.go
docs/advanced-features/http-api/index.md
docs/advanced-features/metrics/index.md
pkg/api/update/update.go
pkg/api/update/update_test.go

Enhances the HTTP API `/v1/update` endpoint to return structured JSON responses instead of plain text, providing comprehensive update operation results for better automation and monitoring capabilities.
- **API Response Format**: Transformed `/v1/update` endpoint from plain text to structured JSON with summary, timing, and metadata sections
- **Enhanced Data**: Added execution timing (milliseconds and human-readable), UTC timestamps, and API version information
- **HTTP Status**: Changed from 202 Accepted to 200 OK for synchronous operations
- **Function Signatures**: Updated to return metrics for improved data flow and testability
- **Test Coverage**: Comprehensive JSON response validation with timing and metadata checks
- **Documentation**: Updated API docs with new response format, …

feat: Enhance HTTP API update endpoint with structured JSON response

---

docs/notifications/overview/index.md

This PR updates Watchtower's Signal notifications documentation to align with recent changes in Shoutrrr's Signal service implementation. The updates address the removal of the deprecated `signals://` scheme and standardize TLS configuration using the `disabletls` query parameter.
- Updated the HTTP configuration example to use `signal://...?disabletls=yes` instead of the removed `signals://` scheme
- Added a TLS Configuration section explaining HTTPS and HTTP usage options

docs(notifications): Update Signal notifications documentation to reflect Shoutrrr changes

---

CHANGELOG.md
cliff.toml

Fixes spacing issue in changelog where git author was concatenated with "in" without a space.
- Modified `cliff.toml` to remove whitespace trimming before "in" in the changelog template  
- Regenerated `CHANGELOG.md` using git-cliff to apply the fix to all existing entries

docs(changelog): correct spacing between author and PR reference

---

.github/workflows/release-dev.yaml
.github/workflows/release-prod.yaml

This is intended to resolve a "Resource not accessible by integration" error during changelog generation.
- Use GitHub PAT due to restrictions placed on forks.

ci(release): update token to CHANGELOG_PAT

---

docs/notifications/template-preview/index.md
docs/notifications/templates/index.md
pkg/notifications/common_templates.go
pkg/notifications/shoutrrr_test.go

Fixes missing report notifications in monitor-only mode when `WATCHTOWER_NOTIFICATION_REPORT=true`.
When running Watchtower in monitor-only mode with report notifications enabled, the report notification was empty and skipped. The "default" template only displayed a session summary (scanned/updated/failed counts) if there were updated or failed containers. Since monitor-only mode doesn't perform updates, it fell back to displaying log entries—which are debug-level and not captured in notifications—resulting in empty messages.
Modified the "default" notification template to always show the session summary when report data exists, regardless of update outcomes. This ensures monitor-only runs provide meaningful feedback (e.g., "49 Scanned, 0 Updated, 0 Failed").
- Modify default template in …

fix(notifications): send report notifications in monitor-only mode

---

cmd/root.go
docs/configuration/arguments/index.md
internal/actions/mocks/client.go
internal/actions/update_test.go
internal/flags/flags.go
pkg/container/client.go
pkg/container/container_target.go
pkg/container/container_test.go
pkg/container/mocks/Client.go
pkg/types/update_params.go

Watchtower fails to update containers with `deploy.resources.limit.cpus` set in Podman rootless mode due to conflicting CPU settings ("NanoCpus conflicts with CpuPeriod and CpuQuota"). This PR adds a new `--cpu-copy-mode` flag that provides automatic Podman detection and configurable CPU handling to resolve the issue.
The flag supports three modes:
- `auto` (default): Automatically detects Podman and filters `NanoCpus` for compatibility
- `full`: Copies all CPU settings unchanged (preserves original behavior)  
- `none`: Strips all CPU limits to avoid conflicts
- Added `--cpu-copy-mode` flag to `internal/flags/flags.go`
- Implemented Podman detection in `pkg/container/client.go` using Docker API `Info()`
- Added CPU filtering logic in `pkg/container/container_target.go`
- Updated …

feat: Add --cpu-copy-mode flag for Podman CPU compatibility

---

cmd/root.go
docs/configuration/arguments/index.md
internal/flags/flags.go

This PR addresses issues with misleading and verbose logging in Watchtower's scheduling and run modes, ensuring users receive accurate information about update behavior.
- **Refactored `logScheduleInfo`**: Replaced nested if-else with a switch statement for better readability and added specific cases for all run modes, including HTTP API variants.
- **Improved logging accuracy**: Corrected messages for `--update-on-start` and default periodic modes to reflect actual behavior.
- **Reduced verbosity**: Demoted non-essential startup logs (e.g., filtering info) to debug level.
- **Enhanced debug logging**: Added detailed logs for schedule spec retrieval and flag processing.
- **Updated documentation**: Clarified `--update-on-start` behavior in the arguments doc.
- **Code quality**: Eliminated …

fix: improve logging clarity and accuracy for scheduling modes

---

pkg/container/image.go
pkg/registry/digest/digest.go
pkg/registry/digest/digest_test.go

Watchtower's self-update process was failing with misleading error messages due to improper handling of registry responses. The code attempted JSON unmarshaling on plain text 404 responses, causing "cannot unmarshal number into Go value" errors and logging "pull failed" even when updates succeeded.
- Digest extraction assumed all responses were JSON manifests
- No validation of response format before parsing
- Misleading logging that confused manifest retrieval failures with image pull failures
- Lack of Content-Type header validation for different registry implementations
Enhanced the digest parsing logic with:
- JSON format detection before unmarshaling
- Content-Type header validation for manifest responses
- Improved error handling and logging
- Comprehensive test coverage for edge …

Fix: Improve self-update handling with robust digest parsing

---

cmd/root_test.go
internal/actions/update_test.go

This PR addresses random test failures observed in GitHub Actions CI. The failures were caused by timing-sensitive tests that behaved inconsistently under CI load and across different operating systems.
**Changes:**
- **cmd/root_test.go**: Made timing assertions more resilient to CI variability
- `TestAwaitDockerClient`: Widened timing assertion range from `>=1s <2s` to `>=900ms <3s`
- `TestUpdateLockSerialization`: Increased simulation sleep from 10ms to 100ms
- `TestConcurrentScheduledAndAPIUpdate`: Increased sleeps from 50ms/100ms to 100ms/200ms
- **internal/actions/update_test.go**: Fixed safeguard delay test
- Changed `PullFailureDelay` from 1ms to 10ms to prevent timing failures on slower systems

Fix random test failures in CI by improving timing reliability

---

.github/workflows/test.yaml

Pin Go version to 1.25.1 to resolve failures due to mismatched version.

ci: Pin Go version to mitigate version mismatch

---

internal/actions/check.go
pkg/container/container.go
pkg/container/container_test.go

Watchtower panics with "runtime error: invalid memory address or nil pointer dereference" when cleaning up multiple instances, as reported in [Issue #744](https://github.com/nicholas-fedor/watchtower/issues/744). This occurs when Docker's `ImageInspect` fails, leaving `imageInfo` as `nil`, and the `ImageID()` method attempts to dereference it without checking.
- Modified `cleanupExcessWatchtowers` in `internal/actions/check.go` to use `SafeImageID()` instead of `ImageID()` for safe handling of containers with missing image info.
- Updated `Container.ImageID()` in `pkg/container/container.go` to include a nil check, returning an empty string when `imageInfo` is `nil`.
- Added unit tests in `pkg/container/container_test.go` to verify behavior with `nil` imageInfo.
- …

fix: prevent nil pointer dereference in container cleanup

---

cmd/root.go
cmd/root_test.go

GitHub Actions tests were failing due to timeout issues in multi-instance scenarios. The `TestUpdateOnStartMultiInstanceScenario` test was timing out after 10 minutes, and `TestUpdateOnStartLockingBehavior` was hanging indefinitely. Root cause was an inverted lock condition in the shutdown logic that caused improper waiting behavior.
The shutdown code in `runUpgradesOnSchedule` had an inverted condition:
```go
if len(lock) > 0 {  // Wrong: waits when lock is available
<-lock
}
```
This should wait when `len(lock) == 0` (update running), not when `len(lock) > 0` (no update running).
1. **Fixed the inverted lock condition** to properly wait only when updates are running
2. **Added `waitForRunningUpdate` helper function** with timeout protection (30s) to prevent infinite blocking
3. …

fix(cmd): correct shutdown lock waiting logic and prevent test timeouts

---

pkg/registry/auth/auth.go
pkg/registry/auth/auth_test.go
pkg/registry/digest/digest.go
pkg/registry/digest/digest_test.go
pkg/registry/manifest/manifest.go
pkg/registry/manifest/manifest_test.go

This PR fixes a regression in version 1.12.0 where digest retrieval was failing with "registry responded with invalid HEAD request: status 404 Not Found" for many containers, causing watchtower to fall back to expensive full image pulls. The issue was caused by improper handling of HTTP redirects during authentication and manifest requests.
- **pkg/registry/auth/auth.go**: Added redirect detection to `GetToken()` and `handleBearerAuth()`, special handling for lscr.io registry authentication to avoid regression, added `LSCRRegistry` constant
- **pkg/registry/auth/auth_test.go**: Updated tests to handle new return values, added test cases for redirect scenarios
- **pkg/registry/digest/digest.go**: Refactored manifest URL building, added redirect handling in `handleManifestResponse()`, …

Fix: Digest retrieval failed, falling back to full pull

---

pkg/api/update/update.go

Fixed I/O blocking in the HTTP API update handler that was causing `TestConcurrentScheduledAndAPIUpdate` to timeout after 10 minutes in CI environments. The handler was attempting to copy the request body to stdout, which blocks when stdout is piped in test/CI environments.
- **pkg/api/update/update.go**:
- Replaced `io.Copy(os.Stdout, r.Body)` with `io.Copy(io.Discard, r.Body)` to safely discard the request body
- Removed unused `"os"` import
- Updated comment from "Log request body to stdout for debugging" to "Discard request body to prevent I/O blocking in tests and CI environments"

fix(api): prevent I/O blocking in API update handler
